### ISSUE TITLE
Dell Precision 5550 - Sleep issues with S4

### ISSUE THREAD

**Issue by hoaug-tran** [jkbuha/XPS-9500-IceLake-OpenCore#14] opened 2024-04-25 08:44 UTC
Hello 

This project is truly a masterpiece. Congratulations on completing it successfully 

I'm using a Dell Precision 5550 laptop. I've tried doing most of the same things as you but I still can't Hibernate. When I press Sleep, the keyboard light turns off but the fan doesn't turn off. 

Here is my kexts folder and ACPI folder:

![image](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/92006941/157256bf-66f6-45e3-9b9b-786c55b71aac)

![image](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/92006941/99a7046b-2906-441d-a1ff-3739480b1e4a)

I tried use command: `pmset -g log | grep -e "Sleep.*due to" -e "Wake.*due to"` to find some logs about sleep but it doesn't give me anything.

![image](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/92006941/f3eb1611-dd0d-42cf-8c92-b29f4f4ff892)

I don't know why? If you know, can you give me some suggestions? 

And. Here is my config.plist. If you have time, please check it for me. 

[Config.zip](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/files/15106841/Config.zip)

Hope you have nice day. Thank you very much !

**Comment by jkbuha** [comment] 2024-04-25 09:19
you need to 
pmset -a hibernatemode = 25
pmset -a standby = 0

in terminal first. also just double check your S3 and S4 sleep settings are enabled in BIOS using modgrubShell (setup_var_cv Setup 0xE 01)

**Comment by hoaug-tran** [comment] 2024-04-25 11:41
Thanks for answering. I tried doing as you said but it still doesn't work. Hibernate look like working but when I wake it up I just get a black screen. I took a screenshot when I entered the command in Modgrub: 

![image](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/92006941/e0b09563-d866-46d7-972d-11c20084b531)


I have a few questions about your EFI:
- For my Precision 5550 machine, do I need kext AGPMInjector.kext?
- I use RealtekCardReader + RealtekCardReaderFriend to Enable my SD Card Reader. For yours, use Sintekek-rtsx. Don't know if that is the problem?
- Also do I need: SSDT-SRAM.aml, SSDT-TERM.aml or not ?


and I try searching for ACPI S3 from the original BIOS and I see that it is enabled by default 0xE 0x1

![image](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/92006941/2223617d-39e8-4404-a153-b350bd22f279)

**Comment by jkbuha** [comment] 2024-04-25 13:13
That's the problem. ACPI S3 is disabled (and as a result S4 won't work
either).

Disable "Block S3 sleep" option in BIOS (ie: S3 sleep should now be
enabled) and then try this in modgrubshell:

setup_var_cv Setup 0xE 00 01

ᐧ

**Comment by hoaug-tran** [comment] 2024-04-25 23:32
my BIOS just have option Block Sleep ( i think it is the same with Block S3 Sleep ). i also set it to Disabled.

I tried command: `setup_var_cv Setup 0xE 00 01` then Hibernation works but only works the first time. When I Sleep the second time I get a black screen. I wonder if it's due to iGPU config or not

**Comment by jkbuha** [comment] 2024-04-26 13:12
I suspect this could be a recurrent bug due to powernap. Try this: when the black screen happens, close the lid for 10 seconds then open the lid and see if it works.

**Comment by hoaug-tran** [comment] 2024-04-27 10:05
I tried them all but none of them worked.

**Comment by yago85** [comment] 2024-05-07 09:51
> I tried them all but none of them worked.

Try disabling any third-party applications and test sleep on a clean system. In my case, if the Dell monitor utility is running, the same thing happens with sleep mode as in yours, the same thing happens when using Mac fan control. But if you turn off all these programs, then sleep works fine. I haven't figured out what the problem is yet.

**Comment by jkbuha** [comment] 2024-08-10 11:53
To properly remove the occasional blackscreen issue on hibernation you need to do two things:

1. Disable RTC wake scheduling (as per my recent commit)
2. pmset -a womp 0 && pmset -a proximitywake 0

Closing this thread now, but please reopen if you still have issues.

**Closed as completed by jkbuha** 2024-08-10 11:53 UTC
